version: '3.1'

services:

  db:
    image: mysql
    container_name: ${CONTAINER_NAME}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '${CONTAINER_PORTS}'