version: '3.1'

services:

  db:
    image: mysql
    container_name: api-sales-management
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sales-management-db
    ports:
      - '3307:3306'